version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-example}
    volumes:
      - mongodb_data:/data/db
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - ai-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://${MONGO_ROOT_USER:-root}:${MONGO_ROOT_PASSWORD:-example}@mongodb:27017/chat_db?authSource=admin
      - AI_BASE_URL=http://ollama:11434
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      - mongodb
      - ollama
    networks:
      - ai-network

  frontend:
    build: 
      context: ./ai-ui
      dockerfile: Dockerfile
    container_name: ai_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - ai-network

volumes:
  mongodb_data:
  ollama_models:

networks:
  ai-network:
    driver: bridge
